name: flutter_zoom_drawer
description: A Flutter package with custom implementation of the Side Menu (Drawer)
version: 3.1.1+1
homepage: https://github.com/medyas/flutter_zoom_drawer

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

flutter: null
